### PR TITLE
The context menu would incorrecly open another context menu, because it ...

### PR DESCRIPTION
**Pull request by NsdWorkBook**
...only looked at the trigger for the existing context menu, and not the one targeted

### CODE REVIEW

**Comment by bbrala** [comment]
Ok cool, so basically if you have a context menu triggering on left mouse and one on right mouse this would fix opening both?

**Comment by NsdWorkBook** [comment]
Yep that's the intention.

**Comment by bbrala** [comment]
I tried to reproduce the the problem to write a test, but i wasnt able to. When i add a left click and a right click contextMenu to an element they behave like they shot. Do you have a testcase for me where the problem is appearant?

**Comment by NsdWorkBook** [comment]
Ill try and make a test case for you.

**Comment by bbrala** [comment]
Thank you :)

**Comment by RareDevil** [comment]
I have made a small sample that shows this problem.
http://jsfiddle.net/RareDevil/c2ws3pc9/2/
If you left click the blue background then left click on one of the green boxes then that would open one of those.
you can also right click on one of the green boxes and then right click on the blue box for same result

**Comment by bbrala** [comment]
Fixed in other pull request.

**Pull request closed without merging**
